package com.e.firebasedemoapp;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    EditText firstName;
    EditText lastName;
    Button addButton;
    Button displayButton;
    DatabaseReference databaseReference;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        firstName = findViewById(R.id.firstname);
        lastName = findViewById(R.id.lastname);
        displayButton = findViewById(R.id.display_user);
        displayButton.setOnClickListener(this);
        addButton = findViewById(R.id.add_user);
        addButton.setOnClickListener(this);

        FirebaseDatabase firebaseDatabase = FirebaseDatabase.getInstance();
        databaseReference = firebaseDatabase.getReference("People");


    }

    @Override
    public void onClick(View v) {

        switch (v.getId()) {


            case R.id.add_user:


                String strFn = firstName.getText().toString();
                String strln = lastName.getText().toString();
// To get the unique key automatically generated by Firebase
                String strKey = databaseReference.push().getKey();

                PeopleModel peopleModel = new PeopleModel();
                peopleModel.setPeople_id(strKey);
                peopleModel.setPeople_fn(strFn);
                peopleModel.setPeople_ln(strln);

// To add the value in Database
                databaseReference.child(strKey).setValue(peopleModel);

                firstName.setText("");
                lastName.setText("");


                break;

            case R.id.display_user:

                Intent i = new Intent(MainActivity.this,DataDisplayActivity.class);
                startActivity(i);
                finish();
                break;
        }


    }
}
